name: icu4x
repository: https://github.com/unicode-org/icu4x

publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  ffi: ^2.0.0
  code_assets: ^0.19.0
  hooks: ^0.19.0
  meta: ^1.16.0
  crypto: ^3.0.6
  collection: ^1.19.1
  path: ^1.9.1
  args: ^2.7.0
  native_toolchain_c:
    path: ../../../native/pkgs/native_toolchain_c
  record_use: ^0.4.1
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0


dependency_overrides:
  native_toolchain_c:
    path: ../../../native/pkgs/native_toolchain_c
