name: icu4x
description: > 
  Dart bindings for the Rust icu4x crate.
version: 0.1.0-dev
repository: https://github.com/unicode-org/icu4x/tree/main/ffi/dart
issue_tracker: https://github.com/unicode-org/icu4x/issues?q=is%3Aissue%20is%3Aopen%20label%3AU-flutter

platforms:
  # web: Not supported for now.
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - i18n

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  ffi: ^2.0.0
  code_assets: ^0.19.0
  hooks: ^0.19.0
  meta: ^1.16.0
  crypto: ^3.0.6
  collection: ^1.19.1
  path: ^1.9.1
  args: ^2.7.0
  native_toolchain_c: ^0.16.8
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0

hooks:
  user_defines:
    icu4x:
      buildMode: checkout
      checkoutPath: ../../
